### ISSUE TITLE
Grass grows way faster than in the original game

### ISSUE THREAD

**Issue by Vulcalien** [beatyeeter/Minimods#1]
I don't know if this is intentional, but the grass grows at 40 times of the speed in the original game.

The reason for this is a missing line in the tick function of GrassTile:

```java
	/** Update method, updates (ticks) every 60 seconds. */
	public void tick(Level level, int xt, int yt) {
		// MISSING LINE vvv
		if (random.nextInt(40) != 0) return;
		// MISSING LINE ^^^

		int xn = xt; // next x position
		int yn = yt; // next y position

		if (random.nextBoolean()) // makes a random decision of true or false
			xn += random.nextInt(2) * 2 - 1; // if that decision is true, then the next x position = (random value between 0 to 1) * 2 - 1
		else
			yn += random.nextInt(2) * 2 - 1; // if that decision is false, then the next y position = (random value between 0 to 1) * 2 - 1

		if (level.getTile(xn, yn) == Tile.dirt) { // if the next positions are a dirt tile then...
			level.setTile(xn, yn, this, 0); // set that dirt tile to a grass tile
		}
	}
```

I have not checked for the other tiles, but I believe there is the same problem in some other tile.

**Comment by spacebytee** [comment]
This is definitely not intentional, I'm not sure where I grabbed the original Minicraft source code when I made the few modifications years ago, but I can't seem to find the variation of the source code with the comments in it to compare, I did find the original Ludum Dare source code, and updated the repository, I'll build a new version at some point, and maybe fix it up, as this project is very old. It might make more sense just to remake it entirely.
